---
- name: Get information about Pull requests on Bitbucket repository
  hosts: localhost
  become: false

  tasks:

  - name: Get pull requests on repository
    esp.bitbucket.bitbucket_pull_request_info:
      username: SVCxxxxxx
      password: secret
      repository: bar  # alias: name
      project_key: FOO
      validate_certs: no
    register: ebi_pull_request_info_output

  - debug:
      var: ebi_pull_request_info_output