---
- name: Read file contents from Bitbucket Server
  hosts: localhost
  become: false

  tasks:

  - name: lookup | Read file contents from Bitbucket Server
    ansible.builtin.debug:
      msg: "{{ lookup('esp.bitbucket.bitbucket_file', 'path/to/baz.yml', 
               project_key='FOO', repository='bar', validate_certs='no', 
               username='SVCxxxxxx', password='secret') 
               | b64decode
               | from_yaml }}"  

  - name: lookup | Display multiple files contents
    ansible.builtin.debug:
      msg: "{{ item | b64decode }}"
    loop: "{{ query('esp.bitbucket.bitbucket_file', 'path/to/baz.yml', 'qux.json',
              project_key='FOO', repository='bar', at='master', validate_certs='no', 
              token='MjA2M...hqP58' ) }}"
    loop_control:
      label: "[Processing a file from Bitbucket Server ..]"

  - name: lookup | Read vaulted file, do not decrypt it
    ansible.builtin.debug:
      msg: "{{ lookup('esp.bitbucket.bitbucket_file', 'path/to/vault.yml', 
               project_key='FOO', repository='bar', validate_certs='no', 
               username='SVCxxxxxx', password='secret', unvault='no' ) 
               | b64decode
               | from_yaml }}" 

  - name: lookup | Read vaulted file, decrypt it
    ansible.builtin.debug:
      msg: "{{ lookup('esp.bitbucket.bitbucket_file', 'path/to/vault.yml', 
               project_key='FOO', repository='bar', at='master', validate_certs='no', 
               token='MjA2M...hqP58', unvault='yes' ) 
               | b64decode
               | from_yaml }}" 
